//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMS.Lang.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data Management.
        /// </summary>
        internal static string basicdata {
            get {
                return ResourceManager.GetString("basicdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string closebtn {
            get {
                return ResourceManager.GetString("closebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Type Configuration.
        /// </summary>
        internal static string dept {
            get {
                return ResourceManager.GetString("dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Type Configuration.
        /// </summary>
        internal static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Type Configuration.
        /// </summary>
        internal static string empolyee {
            get {
                return ResourceManager.GetString("empolyee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string loginbtn {
            get {
                return ResourceManager.GetString("loginbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Human Resource Management System.
        /// </summary>
        internal static string loginform {
            get {
                return ResourceManager.GetString("loginform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Human Resource Management System.
        /// </summary>
        internal static string logintitle {
            get {
                return ResourceManager.GetString("logintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Human Resource Management System.
        /// </summary>
        internal static string mainform {
            get {
                return ResourceManager.GetString("mainform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Type Configuration.
        /// </summary>
        internal static string nation {
            get {
                return ResourceManager.GetString("nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook Type Configuration.
        /// </summary>
        internal static string notebook {
            get {
                return ResourceManager.GetString("notebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Political Status Configuration.
        /// </summary>
        internal static string politicalstatus {
            get {
                return ResourceManager.GetString("politicalstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Punishment Configuration.
        /// </summary>
        internal static string rnp {
            get {
                return ResourceManager.GetString("rnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Type Configuration.
        /// </summary>
        internal static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Type Configuration.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
